export enum pageEnums {
  HOME = "/",
  LOGIN = "/login",
  SIGNUP = "signUp",
  ABOUT = "about",
  BLOGS = "blogs",
  SERVICES = "services",
  HOTELS = "hotels",
  FLIGHTS = "/flights",
  ID = ":id",
  PROFILE = "profile",
  ADDBLOG = "/addBlog",
  PAY = "/pay",
  bLOGID = "/blog/:blogId",
}
